### ISSUE TITLE
Getting started with Docker 

### ISSUE THREAD

**Issue by raziiiuddin** [Crio-Bytes/Miscellaneous#10]
**MicroByte Title:** Getting Started with Docker

**Domain:** Docker, Containers, Cloud, DevOps, Spring(Java)

**Scope of learning for learners:** 
* Fundamental concepts of Containers and Docker
* Use Docker to containerize an application 
* Use Docker Hub to share container images

**Activities:** 
* Build a Spring Application
* Make a Dockerfile
* Build a container image and run a container
* Share container images using docker hub 
* Run the application on other machine

**Comment by YourAKShaw** [comment]
@raziiiuddin Kindly edit the scope of learning to list bullet points.

**Comment by YourAKShaw** [comment]
Also don't make it tutorialish, as your description is giving the vibe of it.

**Comment by raziiiuddin** [comment]
Done

**Comment by YourAKShaw** [comment]
Awesome! Waiting for a quality MicroByte now. :smile_cat:
