### ISSUE TITLE
Linear Regression with Regularization

### ISSUE THREAD

**Issue by itsadityagupta** [Crio-Bytes/Miscellaneous#24]
**MicroByte Title:** Linear Regression with Regularization

**Domain:** Machine Learning

**Scope of learning for learners:** 

1. Basic Data Analysis
2. Linear Regression Implementation
3. Ridge Regression Implementation
4. Lasso Regression Implementation
5. ElasticNet Regression Implementation

**Activities:** 

1. Activity 1 - Understand the dataset given and implement the Linear Regression Model.
2. Activity 2 - Perform analysis for assumptions to be satisfied for Linear Regression by the dataset.
3. Activity 3 - Implement Ridge, Lasso, and ElasticNet Regression and compare their performances.

**Comment by sudhanshutiwari264** [comment]
@Aditya-Gupta1  Kindly edit the scope of learning to list bullet points.
Also don't make it tutorialish, as your description is giving the vibe of it.

**Comment by sudhanshutiwari264** [comment]
@Aditya-Gupta1  Waiting for a quality MicroByte now. 😸!

**Comment by itsadityagupta** [comment]
@sudhanshutiwari264 I have updated the scope of learning. Also, it was my mistake that the description sounded tutorialish. I think, now the issue description is fine.
Please let me know of any further changes.
Thanks.
