### ISSUE TITLE
Building a Decoupled Voice Assistant

### ISSUE THREAD

**Issue by sudiptog81** [Crio-Bytes/Miscellaneous#3]
**MicroByte Title:** Building a Decoupled Voice Assistant

**Domain:** 
- Web
- Human Computer Interaction
- System Design

**Scope of learning for learners:** 

- Browser APIs
- Serverless Functions
- Web Development
- DevOps

**Activities:**

- Utilising Web Speech APIs
- Writing Serverless Functions
- Building a Basic Front-End
- Interacting with Serverless Functions using Fetch API
- Deploying an Application to Production

**Comment by amoghrajesh** [comment]
Hey @sudiptog81 you can start working on it 
Keep in mind the learn by doing approach and the PR structure as you might already be aware of
All the best!
