### ISSUE TITLE
New microbyte for Understanding Interfaces in Java

### ISSUE THREAD

**Issue by srishti-034** [Crio-Bytes/Miscellaneous#33]
**MicroByte Title:** Interfaces in Java

**Domain:** Object Oriented Programming(Java)

**Scope of learning for learners:** 
   

- Creating Interfaces in Java
- Abstract Methods
- Inheriting Interfaces
- Method Overriding

**Activities:** <give a brief idea about what sort of activities this MicroByte will contain>

- Activity 1(Understanding abstract methods) : Contains brief explanation of abstract methods along with a micro-challenge/ task for the learner.
- Activity 2(Creating Interfaces in Java): A brief explanation of interfaces along with references and syntax. A micro-challenge/ task for learner to create an interface according to the specified requirements.
- Activity 3(Inheritance and Using Interface): Activity to create two new Classes, inheriting the Interface and implementing the overridden abstract methods.

**Comment by Kevinpaulose05** [comment]
Everything is nicely done. Just the thing is wrong topic. Please open the issue under DSA topic

**Comment by Ak-Shaw** [comment]
@Kevinpaulose05 No. Interfaces is a concept of OOP. This is the right repo for now for it. @srishti-034 kindly move on.
