### ISSUE TITLE
[Creators] Add a detailed data analysis activity

### ISSUE THREAD

**Issue by itsadityagupta** [Crio-Bytes/Miscellaneous#39]
**MicroByte Title:** Linear Regression with Regularization

**Improvement Proposal:** 

Make an activity preceding the first activity in the micro-byte, which does the following:
* Performs a detailed Data Analysis for the given dataset.
* Perform outlier detection and removal.
* Perform Feature Engineering.
* Perform Feature Selection.
* Save the preprocessed data frame along with the original dataset.

After you have the preprocessed form of the dataset, you can extend **Activity 1** by using a different linear regression model trained on new preprocessed data and show the reduction in error which a simple preprocessing can lead to.

**Benefits of proposed improvements:**

Users will get a practical intuition of the increase in the performance or reduction in the error, to which a carefully preprocessed dataset can lead to

**Comment by rutujak24** [comment]
Can I take up this issue?

**Comment by itsadityagupta** [comment]
Sure. Go Ahead.

**Comment by rutujak24** [comment]
Hey, @Aditya-Gupta1 Should I need to add the data analysis on the jupyter notebook in the activity 1 folder?

**Comment by sudhanshutiwari264** [comment]
@rutujak24 Assigning this to you !
Waiting for your contribution 🎉

**Comment by rutujak24** [comment]
Thanks, @sudhanshutiwari264 
I have made the contribution and resolved this issue, here it is: https://github.com/Crio-Bytes/Miscellaneous/pull/65

**Comment by itsadityagupta** [comment]
@rutujak24 Great Work!! But additionally, I also mentioned preprocessing data and applying linear regression to that preprocessed dataset. This will demonstrate a low test error on the same dataset and learners can have a practical example of how preprocessing can lead to effective modeling.
You can add this part in activity 5 itself.

**Comment by rutujak24** [comment]
> @rutujak24 Great Work!! But additionally, I also mentioned preprocessing data and applying linear regression to that preprocessed dataset. This will demonstrate a low test error on the same dataset and learners can have a practical example of how preprocessing can lead to effective modeling.
> You can add this part in activity 5 itself.

Thanks @Aditya-Gupta1 
I guess whatever I have done is pretty much enough the data analysis, the regression part which you are speaking about can be added to activity 5 where the modelling would be described. So it should be included in activity 4.

Hence I guess tge PR satisfies all the requirements for detailed data analysis, so should be merged.
