### ISSUE TITLE
Cross-Platform App using Python

### ISSUE THREAD

**Issue by kaustubhgupta** [Crio-Bytes/Miscellaneous#4]
**MicroByte Title:** Cross-Platform App using Python

**Domain:** Python, Usage of APIs, Kivymd, a bit of UI/UX

**Scope of learning for learners:** This micro byte will walk you through the basics of building an app in Python. Here I will briefly discuss various components to be used, how to fetch data from API, and process in the background to be presented to the user. All the code will be written in Python and a bit of kivy lang which is very easy to understand. I will not explain the conversion part (python file to apk) in detail and just an overview as that is a wide domain and requires a separate byte but the application build is cross-platform. 

- A very good example of this is PyDelhi 2019. They build an android app in Python for their annual conference! 
- I build a university result portal android app which fetches data of around 13k students

**Activities:** Some activities include: 
- Basic layout of the app
- Binding input with output
- Integrating API with I/O
- How to convert it to APK

**Comment by amoghrajesh** [comment]
Hey @kaustubhgupta you can start working on this.
Keep in mind the learn by doing approach and the guidelines for creating the PR as you might be aware of already
All the best!
