### ISSUE TITLE
Hadoop Cluster

### ISSUE THREAD

**Issue by Nitesh-thapliyal** [Crio-Bytes/Miscellaneous#44]
**MicroByte Title:**  Hadoop Cluster

**Domain:**  Big data management

**Scope of learning for learners:** 
- Creating Namenode(masternode)
- Creating Datanode(slavenode)
- Creating Clientnode
- Uploading and Reading file in Hadoop
- Reading files in a terminal and in WebUi of Hadoop

**Activities:** 
- Activity 1 ( Creating Namenode ): contains the explanation of how we can create Namenode by configuring the XML files in Hadoop and contains **Task** for the learners.
- Activity 2 ( Starting Namenode ): contains the explanation of how we can Start Datanode and check whether the datanode is started or not. Contains **Task** for the learners.
- Activity 3 ( Creating Datanode ): contains the explanation of how we can Create Datanode and it contains **Task** for the learners.
- Activity 4 ( Starting Datanode ): contains an explanation of how we can start Datanode and it contains **Task** for the learners.
- Activity 5:  checked datanodes are connected with master and given the task to connect two or more Datanodes.
- Activity 6 : ( creating Clientnode) : contains an explanation of how we can create Client node and contains **Task** for the learners.
- Activity 7: Uploaded and read files in Hadoop.
- Activity 8 (Checking file in Hadoop) : contains the explanation of how we can check files that we have uploaded in Hadoop by the terminal as well as in WebUI.

**Comment by amoghrajesh** [comment]
Hey @Nitesh-thapliyal try to find an application of this too and try to work towards that in this MicroByte.
I am pushing you because you have done this before and quality will improve if you try along this line.
All the best!
