### ISSUE TITLE
[Creators] Add a activity to limit the size of Storage of Datanode.

### ISSUE THREAD

**Issue by Nitesh-thapliyal** [Crio-Bytes/Miscellaneous#50]
**MicroByte Title:** Hadoop Cluster

**Improvement Proposal:** 
- Make an activity in the Microbyte that explains how we can limit the size of storage of Datanode provided to Masternode

**Benefits of proposed improvements:** 
By default when Datanode is connected to the Masternode , Datanode provides its all storage to the Masternode but we can control it , with the help of the proposed improvement you can provide limited storage or the desired amount of storage to the Masternode.

**Comment by amoghrajesh** [comment]
Hey @Nitesh-thapliyal this issue is for learners right? 
If yes, you can rename the [creators] in the title to [learners]
