### ISSUE TITLE
Coding and Debugging

### ISSUE THREAD

**Issue by deepak-prajapatii** [Crio-Bytes/Miscellaneous#51]
MicroByte Title: Coding and Debugging

Domain: Android Development (Java)

Prerequisites:
Need to know Basic Java, DSA, and Algorithm.
Knowledge of Android Studio.

Activities:
1. Layout Improvement in activity_main.xml
2. Coding Phase in the MainActivity.java

**Comment by sudhanshutiwari264** [comment]
@deepak-prajapatii Assigning this to you !

**Comment by deepak-prajapatii** [comment]
> @deepak-prajapatii Assigning this to you !

I'll try to improve it.

**Comment by deepak-prajapatii** [comment]
> > @deepak-prajapatii Assigning this to you !
> 
> I'll try to improve it.

@sudhanshutiwari264 Hello, I am a beginner so I can't understand properly what the assigning means here. Please explain.

**Comment by sudhanshutiwari264** [comment]
@deepak-prajapatii No need to worry man!
Assigning just refers to the person who will be responsible to resolve the issue!
This makes workflow simple!

**Comment by deepak-prajapatii** [comment]
> @deepak-prajapatii No need to worry man!
> Assigning just refers to the person who will be responsible to resolve the issue!
> This makes workflow simple!

@sudhanshutiwari264 I created this issue for learners so that learners will come and solve that issue. But  I can't understand why you are assigning me this task that is actually created for learners.
