### ISSUE TITLE
My Notes 

### ISSUE THREAD

**Issue by deepak-prajapatii** [Crio-Bytes/Miscellaneous#74]
MicroByte Title: My Notes

Domain: Android App Development

Scope of learning for learners:
1. Solutions are not given straight away.
2. Learners can contribute by #LearnByDoingApproach

Activities:
1. Fix Layout
2. Coding Phase

**Comment by amoghrajesh** [comment]
Okay @deepak-prajapatii assigning this one to you. 
We will review the PR asap.
