### ISSUE TITLE
Sketchify your Photo Microbyte

### ISSUE THREAD

**Issue by rutujak24** [Crio-Bytes/Miscellaneous#80]
**MicroByte Title:** Sketchify your Photo Microbyte

**Domain:** Python, ML, Open CV

**Scope of learning for learners:** Understand and implement basics of open cv with a real-time algorithm that the photo editor app uses for making a pencil sketch.

**Activities:** The activity will include a pencil sketch generation from a photo using fundamentals of open cv.

**Comment by rutujak24** [comment]
Please assign this issue to me :)

**Comment by amoghrajesh** [comment]
Hey @rutujak24! You can take it and start working on it.
Keep in mind that the byte shouldn't be like a tutorial and a learner needs to learn by doing. (No direct theory / code)
For convenience, have a look at these micro bytes - [this](https://github.com/Crio-Bytes/System-Design/tree/main/Traffic%20Cop%20-%20Learn%20Load%20Balancer%20using%20HAProxy) and [this](https://github.com/Crio-Bytes/Miscellaneous/tree/main/Building_a_Decoupled_Voice_Assistant).

All the best!
