### ISSUE TITLE
Face Detection using Chrome Shape Detection API

### ISSUE THREAD

**Issue by jain-yakshit-1** [Crio-Bytes/Miscellaneous#91]
**MicroByte Title:** Face Detection using Chrome Shape Detection API

**Domain:** Miscellanous

**Scope of learning for learners:** Learners will get introduced to unknown Chrome APIs. They will explore and buildout any fancy project out of it.

**Activities:** 
1. Introduction to Shape Detection API.
2. Enable video camera activity.
2. Extracting rectangular co-ordinates of face.
3. Draw rectangular bounds around the face in canvas.
4. Suprise challenge

**Comment by amoghrajesh** [comment]
Hey, @jnana-cetana you can start working on this one. Assigning it to you.
All the best!
Also a small typo in point 5 - Surprise*
